### ISSUE TITLE
Adjust code to chemmacros v6

### ISSUE THREAD

**Issue by Sonja-K** [cgnieder/ghsystem#12]
In combination with chemmacros v6.0, this MWE

```
\documentclass{article}
\usepackage{ghsystem}
\begin{document}
\end{document}
```

results in 

```
! Undefined control sequence.
l.669 \chemmacros_load_module:n
                                {nomenclature}
```

Deleting line 669  in `ghsystem.sty`: `\chemmacros_load_module:n {nomenclature}` should fix that.

**Comment by cgnieder** [comment]
Thanks for this. Will be fixed in the next version.

**Comment by lcnittl** [comment]
Thank you for the fix, @cgnieder -- Is a CTAN release planned in the near future?
